export const MESSAGE_STATUS = {
    SENT: 1,
    DELIVERED: 2,
    READ: 3,
  };
  
  export const ONLINE_STATUS = {
    ONLINE: "ONLINE",
    OFFLINE: "OFFLINE",
  };
  
  export const EVENTS = {
    PING :"PING",
    ADD_CONTACT: "ADD_CONTACT",
    ERROR: "ERROR",
    OFFLINE_EVENTS: "OFFLINE_EVENTS",
    OFFLINE_GROUP_MESSAGES: "OFFLINE_GROUP_MESSAGES",
    OFFLINE_MESSAGES: "OFFLINE_MESSAGES",
    MOBILE_MESSAGES: "MOBILE_MESSAGES",
    SINGLE_CHAT_SEND_MESSAGE: "SINGLE_CHAT_SEND_MESSAGE",
    SINGLE_CHAT_TYPING: "SINGLE_CHAT_TYPING",
    SINGLE_CHAT_DELIVERED: "SINGLE_CHAT_DELIVERED",
    SINGLE_CHAT_READ: "SINGLE_CHAT_READ",
    LAST_MESSAGE: "LAST_MESSAGE",
    LAST_MESSAGE_ALL: "LAST_MESSAGE_ALL",
    DISCONNECT: "disconnect",
    DELETE_CHAT: "DELETE_CHAT",
    USER_ONLINE_STATUS: "USER_ONLINE_STATUS",
    UPDATE_MESSAGE_STATUS: "UPDATE_MESSAGE_STATUS",
    GET_ALL_ONLINE: "GET_ALL_ONLINE",
    PROFILE_UPDATED: "PROFILE_UPDATED",
    GET_MY_CONTACTS: "GET_MY_CONTACTS",
    ONLINE_OFFLINE: "ONLINE_OFFLINE",
    CREATE_GROUP: "CREATE_GROUP",
    ADDED_IN_NEW_GROUP: "ADDED_IN_NEW_GROUP",
    GET_USERS_INFO: "GET_USERS_INFO",
    REPORT_MESSAGE: "REPORT_MESSAGE",
    DELETE_FOR_EVERYONE_CHAT: "DELETE_FOR_EVERYONE_CHAT",
    MESSAGE_DELETED_ON_CHAT: "MESSAGE_DELETED_ON_CHAT",
    BLOCK_CONTACT: "BLOCK_CONTACT",
    UN_BLOCK_CONTACT: "UN_BLOCK_CONTACT",
    GET_BLOCKED_CONTACTS: "GET_BLOCKED_CONTACTS",
    DELETE_FOR_ME: "DELETE_FOR_ME",
    ACK: "ACK",
    PAGE: {
      SINGLE_CHAT: "PAGE_SINGLE_CHAT",
    },
    LOGOUT: "LOGOUT",
  };
  
  export const OFFLINE_STORE = [
    "ADD_CONTACT",
    "SINGLE_CHAT_DELIVERED",
    "ONLINE_OFFLINE",
    "SINGLE_CHAT_READ"
  ]
  